name: Deploy to Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" > .env
      - name: Change Directory
        run: cd ScirptData
      - name: Login to Docker Hub
        run: |
          cd Backend_Edugo
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image MYSQL
        run: |
          cd ScirptData
          docker build -t tkneng/edugo-mysql .
      - name: Push Docker Image MYSQL
        run: |
          cd ScirptData
          docker push tkneng/edugo-mysql:latest
      - name: Build Docker Image Backend
        run: |
          cd Backend_Edugo
          docker build -t tkneng/go-backend .
      - name: Push Docker Image
        run: |
          cd Backend_Edugo
          docker push tkneng/go-backend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Delete Old Container MYSQL
        run: docker rm -f mysql-container
      - name: Delete Old Container
        run: docker rm -f go-backend-container
      - name: Run Docker Container MYSQL
        run: docker run -d --network edugo-network -p 3306:3306 --name mysql-container tkneng/edugo-mysql:latest
      - name: Pull Docker Image Backend
        run: docker pull tkneng/go-backend:latest
      - name: Run Docker Container
        run: docker run -d --network edugo-network -p 8080:8080 --name go-backend-container tkneng/go-backend:latest