name: Deploy to Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Change Directory
        run: cd Backend_Edugo
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" > .env
      - name: Login to Docker Hub
        run: |
          cd Backend_Edugo
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          cd Backend_Edugo
          docker build -t tkneng/go-backend .
      - name: Push Docker Image
        run: |
          cd Backend_Edugo
          docker push tkneng/go-backend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Delete Old Container MYSQL
        run: docker rm -f mysql-container
      - name: Run Docker Container MYSQL
        run: docker run -d -p 3306:3306 --name mysql-container -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} -e LANG=en_US.UTF-8 -v $(pwd)/scirptdb/db.sql:/docker-entrypoint-initdb.d/db.sql -v $(pwd)/scirptdb/insert.sql:/docker-entrypoint-initdb.d/insert.sql -v $(pwd)/scirptdb/user.sql:/docker-entrypoint-initdb.d/user.sql mysql:8.0.33
      - name: Pull Docker Image Backend
        run: docker pull tkneng/go-backend:latest
      - name: Delete Old Container
        run: docker rm -f go-backend-container
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name go-backend-container tkneng/go-backend:latest